"use client";

import { createContext, useContext, useState } from "react";

type AdminLang = "en" | "fa";

interface AdminLangContextValue {
  lang: AdminLang;
  setLang: (l: AdminLang) => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
}

const translations: Record<AdminLang, Record<string, string>> = {
  en: {
    // nav
    guide: "Guide (0 to 100)",
    overview: "Overview",
    appointments: "Appointments",
    calendar: "Calendar",
    clients: "Clients",
    services: "Services",
    portfolio: "Portfolio",
    testimonials: "Testimonials",
    blog: "Blog",
    mediaLibrary: "Media Library",
    seo: "SEO",
    settings: "Settings",
    // header
    welcome: "Welcome",
    signOut: "Sign Out",
    // dashboard
    dashboard: "Dashboard",
    dashboardSub: "Overview of your beauty business",
    totalAppointments: "Total Appointments",
    pending: "Pending",
    confirmed: "Confirmed",
    completed: "Completed",
    cancelled: "Cancelled",
    noShow: "No Show",
    recentAppointments: "Recent Appointments",
    viewAll: "View all →",
    noAppointmentsYet: "No appointments yet",
    client: "Client",
    service: "Service",
    date: "Date",
    booked: "Booked",
    status: "Status",
    // appointments page
    all: "All",
    noAppointmentsFound: "No appointments found",
    phone: "Phone",
    appointment: "Appointment",
    actions: "Actions",
    confirm: "✓ Confirm",
    decline: "✕ Decline",
    reason: "Reason (optional)",
    confirmDecline: "Confirm Decline",
    deleteAppointment: "Delete appointment?",
    // calendar
    noUpcoming: "No upcoming appointments",
    // clients
    name: "Name",
    contact: "Contact",
    tags: "Tags",
    noClientsYet: "No clients yet",
    // pagination
    prev: "Prev",
    next: "Next",
    page: "Page",
    of: "of",
    // page headers
    addNew: "Add New",
    newAppointment: "New Appointment",
    appointmentsDesc: "Manage all booking requests and appointments",
    calendarDesc: "Upcoming confirmed and pending appointments",
    newClient: "New Client",
    clientsDesc: "Manage client profiles and history",
    servicesTitle: "Services",
    servicesDesc: "Manage beauty services",
    newService: "New Service",
    active: "Active",
    inactive: "Inactive",
    portfolioTitle: "Portfolio",
    portfolioDesc: "Manage portfolio categories and gallery items",
    categories: "Categories",
    addCategory: "Add Category",
    addPortfolioItem: "Add Portfolio Item",
    portfolioItems: "Portfolio Items",
    items: "items",
    itemDetails: "Item Details",
    category: "Category",
    linkedService: "Linked Service (optional)",
    image: "Image",
    titleDe: "Title (DE)",
    titleEn: "Title (EN)",
    altTextDe: "Alt Text (DE)",
    altTextEn: "Alt Text (EN)",
    descriptionDe: "Description (DE)",
    descriptionEn: "Description (EN)",
    nameDe: "Name (DE)",
    nameEn: "Name (EN)",
    german: "German",
    english: "English",
    testimonialsTitle: "Testimonials",
    testimonialsDesc: "Manage client reviews",
    addTestimonial: "Add Testimonial",
    featuredLabel: "Featured",
    clientName: "Client Name",
    eventType: "Event Type",
    rating: "Rating (1-5)",
    contentDe: "Content (DE)",
    contentEn: "Content (EN)",
    delete: "Delete",
    edit: "Edit",
    none: "None",
    featured: "Featured",
    slug: "Slug",
    sortOrder: "Sort Order",
    blogDesc: "Manage blog posts and categories",
    newPost: "New Post",
    posts: "Posts",
    save: "Save",
    coverImage: "Cover Image",
    coverImageHint: "Wide cover image (recommended: 1200×630)",
    postSettings: "Post Settings",
    tagsHint: "Tags (comma-separated)",
    draft: "Draft",
    published: "Published",
    archived: "Archived",
    excerptDe: "Excerpt (DE)",
    excerptEn: "Excerpt (EN)",
    newBlogPost: "New Blog Post",
    editBlogPost: "Edit Blog Post",
    mediaLibraryDesc: "Manage images and media assets",
    addMedia: "Add Media",
    altText: "Alt Text",
    folder: "Folder",
    editMedia: "Edit Media",
    email: "Email",
    settingsDesc: "Business info, hours, and blocked dates",
    businessInfo: "Business Information",
    businessName: "Business Name",
    instagramUrl: "Instagram URL",
    location: "Location",
    saveSettings: "Save Settings",
    workingHours: "Working Hours",
    day: "Day",
    startTime: "Start Time",
    endTime: "End Time",
    allDay: "All Day",
    timeHint: 'Format: HH:MM — e.g. "10:00"',
    addRule: "Add Rule",
    blockedDates: "Blocked Dates",
    addBlockedDate: "Add Blocked Date",
    integrations: "Integrations",
    editWorkingHours: "Edit Working Hours",
    // edit pages
    editAppointment: "Edit Appointment",
    appointmentDetails: "Appointment Details",
    clientNotes: "Client Notes",
    internalNotes: "Internal Notes",
    locale: "Locale",
    editClient: "Edit Client",
    clientInfo: "Client Information",
    firstName: "First Name",
    lastName: "Last Name",
    notes: "Notes",
    vipClient: "VIP Client",
    editService: "Edit Service",
    serviceDetails: "Service Details",
    durationMinutes: "Duration (minutes)",
    bufferMinutes: "Buffer (minutes)",
    germanContent: "German Content",
    englishContent: "English Content",
    shortDescDe: "Short Description (DE)",
    shortDescEn: "Short Description (EN)",
    editPortfolioItem: "Edit Portfolio Item",
    editTestimonial: "Edit Testimonial",
    testimonial: "Testimonial",
    type: "Type",
  },
  fa: {
    // nav
    guide: "آموزش صفر تا صد",
    overview: "نمای کلی",
    appointments: "رزروها",
    calendar: "تقویم",
    clients: "مشتریان",
    services: "خدمات",
    portfolio: "پورتفولیو",
    testimonials: "نظرات",
    blog: "وبلاگ",
    mediaLibrary: "کتابخانه رسانه",
    seo: "سئو",
    settings: "تنظیمات",
    // header
    welcome: "خوش آمدید",
    signOut: "خروج",
    // dashboard
    dashboard: "داشبورد",
    dashboardSub: "نمای کلی کسب‌وکار زیبایی شما",
    totalAppointments: "کل رزروها",
    pending: "در انتظار",
    confirmed: "تأیید شده",
    completed: "انجام شده",
    cancelled: "لغو شده",
    noShow: "حاضر نشده",
    recentAppointments: "رزروهای اخیر",
    viewAll: "← مشاهده همه",
    noAppointmentsYet: "هنوز رزروی ثبت نشده",
    client: "مشتری",
    service: "خدمت",
    date: "تاریخ",
    booked: "ثبت در",
    status: "وضعیت",
    // appointments page
    all: "همه",
    noAppointmentsFound: "رزروی یافت نشد",
    phone: "تلفن",
    appointment: "رزرو",
    actions: "عملیات",
    confirm: "✓ تأیید",
    decline: "✕ رد",
    reason: "دلیل (اختیاری)",
    confirmDecline: "تأیید رد",
    deleteAppointment: "حذف رزرو؟",
    // calendar
    noUpcoming: "رزرو آینده‌ای وجود ندارد",
    // clients
    name: "نام",
    contact: "اطلاعات تماس",
    tags: "برچسب‌ها",
    noClientsYet: "هنوز مشتری‌ای ثبت نشده",
    // pagination
    prev: "قبلی",
    next: "بعدی",
    page: "صفحه",
    of: "از",
    // page headers
    addNew: "افزودن",
    newAppointment: "رزرو جدید",
    appointmentsDesc: "مدیریت تمام درخواست‌ها و رزروها",
    calendarDesc: "رزروهای تأیید شده و در انتظار",
    newClient: "مشتری جدید",
    clientsDesc: "مدیریت پروفایل و سابقه مشتریان",
    servicesTitle: "خدمات",
    servicesDesc: "مدیریت خدمات زیبایی",
    newService: "خدمت جدید",
    active: "فعال",
    inactive: "غیرفعال",
    portfolioTitle: "پورتفولیو",
    portfolioDesc: "مدیریت دسته‌بندی‌ها و آیتم‌های گالری",
    categories: "دسته‌بندی‌ها",
    addCategory: "افزودن دسته‌بندی",
    addPortfolioItem: "افزودن آیتم",
    portfolioItems: "آیتم‌های پورتفولیو",
    items: "آیتم",
    itemDetails: "جزئیات آیتم",
    category: "دسته‌بندی",
    linkedService: "خدمت مرتبط (اختیاری)",
    image: "تصویر",
    titleDe: "عنوان (آلمانی)",
    titleEn: "عنوان (انگلیسی)",
    altTextDe: "متن جایگزین (آلمانی)",
    altTextEn: "متن جایگزین (انگلیسی)",
    descriptionDe: "توضیحات (آلمانی)",
    descriptionEn: "توضیحات (انگلیسی)",
    nameDe: "نام (آلمانی)",
    nameEn: "نام (انگلیسی)",
    german: "آلمانی",
    english: "انگلیسی",
    testimonialsTitle: "نظرات",
    testimonialsDesc: "مدیریت نظرات مشتریان",
    addTestimonial: "افزودن نظر",
    featuredLabel: "ویژه",
    clientName: "نام مشتری",
    eventType: "نوع رویداد",
    rating: "امتیاز (۱-۵)",
    contentDe: "متن (آلمانی)",
    contentEn: "متن (انگلیسی)",
    delete: "حذف",
    edit: "ویرایش",
    none: "هیچ‌کدام",
    featured: "ویژه",
    slug: "اسلاگ",
    sortOrder: "ترتیب",
    blogDesc: "مدیریت مطالب و دسته‌بندی‌های وبلاگ",
    newPost: "مطلب جدید",
    posts: "مطالب",
    save: "ذخیره",
    coverImage: "تصویر کاور",
    coverImageHint: "تصویر افقی (پیشنهاد: ۱۲۰۰×۶۳۰)",
    postSettings: "تنظیمات مطلب",
    tagsHint: "برچسب‌ها (با کاما جدا کنید)",
    draft: "پیش‌نویس",
    published: "منتشر شده",
    archived: "بایگانی",
    excerptDe: "خلاصه (آلمانی)",
    excerptEn: "خلاصه (انگلیسی)",
    newBlogPost: "مطلب جدید وبلاگ",
    editBlogPost: "ویرایش مطلب وبلاگ",
    mediaLibraryDesc: "مدیریت تصاویر و فایل‌های رسانه",
    addMedia: "افزودن رسانه",
    altText: "متن جایگزین",
    folder: "پوشه",
    editMedia: "ویرایش رسانه",
    email: "ایمیل",
    settingsDesc: "اطلاعات کسب‌وکار، ساعات کاری و تاریخ‌های مسدود",
    businessInfo: "اطلاعات کسب‌وکار",
    businessName: "نام کسب‌وکار",
    instagramUrl: "آدرس اینستاگرام",
    location: "موقعیت مکانی",
    saveSettings: "ذخیره تنظیمات",
    workingHours: "ساعات کاری",
    day: "روز",
    startTime: "ساعت شروع",
    endTime: "ساعت پایان",
    allDay: "تمام روز",
    timeHint: "فرمت: HH:MM — مثلاً «۱۰:۰۰»",
    addRule: "افزودن قانون",
    blockedDates: "تاریخ‌های مسدود",
    addBlockedDate: "افزودن تاریخ مسدود",
    integrations: "یکپارچه‌سازی‌ها",
    editWorkingHours: "ویرایش ساعات کاری",
    // edit pages
    editAppointment: "ویرایش رزرو",
    appointmentDetails: "جزئیات رزرو",
    clientNotes: "یادداشت مشتری",
    internalNotes: "یادداشت داخلی",
    locale: "زبان",
    editClient: "ویرایش مشتری",
    clientInfo: "اطلاعات مشتری",
    firstName: "نام",
    lastName: "نام خانوادگی",
    notes: "یادداشت",
    vipClient: "مشتری VIP",
    editService: "ویرایش خدمت",
    serviceDetails: "جزئیات خدمت",
    durationMinutes: "مدت زمان (دقیقه)",
    bufferMinutes: "زمان فاصله (دقیقه)",
    germanContent: "محتوای آلمانی",
    englishContent: "محتوای انگلیسی",
    shortDescDe: "توضیح کوتاه (آلمانی)",
    shortDescEn: "توضیح کوتاه (انگلیسی)",
    editPortfolioItem: "ویرایش آیتم پورتفولیو",
    editTestimonial: "ویرایش نظر",
    testimonial: "نظر",
    type: "نوع",
  },
};

const AdminLangContext = createContext<AdminLangContextValue>({
  lang: "en",
  setLang: () => {},
  t: (k) => translations["en"][k] ?? k,
  dir: "ltr",
});

export function AdminLangProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<AdminLang>("en");

  function t(key: string): string {
    return translations[lang][key] ?? translations["en"][key] ?? key;
  }

  return (
    <AdminLangContext.Provider value={{ lang, setLang, t, dir: lang === "fa" ? "rtl" : "ltr" }}>
      {children}
    </AdminLangContext.Provider>
  );
}

export function useAdminLang() {
  return useContext(AdminLangContext);
}
