"use client";

import { createContext, useContext, useEffect, useState } from "react";

const STORAGE_KEY = "admin-lang";

type AdminLang = "en" | "fa";

interface AdminLangContextValue {
  lang: AdminLang;
  setLang: (l: AdminLang) => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
}

const translations: Record<AdminLang, Record<string, string>> = {
  en: {
    discounts: "Discount Codes",
    discountsDesc: "Manage brand offers, discount codes and referral links.",
    discountNew: "Add Discount Code",
    discountEdit: "Edit Discount Code",
    discountDetails: "Brand & discount details",
    discountBrand: "Brand name",
    discountLogo: "Brand logo (optional)",
    discountLogoHint: "Upload a transparent PNG or WebP logo for the cleanest result.",
    discountLogoChoose: "Choose logo",
    discountLogoReplace: "Replace logo",
    discountLogoRemove: "Remove logo",
    discountLabel: "Discount badge",
    discountLabelRequired: "Enter a short discount badge, such as 20% OFF.",
    discountInvalidLogo: "Upload a valid logo image.",
    discountClicks: "Shop clicks",
    discountCode: "Discount code",
    discountUrl: "Brand shop / referral URL",
    discountUrlHint: "Paste the complete link provided by the brand, including any referral parameters.",
    discountExpiry: "Expiry date (optional)",
    discountExpiryHint: "Valid through the end of this day in Germany. Leave blank for no expiry.",
    discountNoExpiry: "No expiry",
    discountExpired: "Expired",
    discountPublish: "Show this offer on the website",
    discountPublishHint: "Expired offers are hidden automatically, even when this is checked.",
    discountOfferDe: "Offer headline (DE)",
    discountOfferEn: "Offer headline (EN)",
    discountTermsHint: "Use the descriptions for the brand’s conditions, exclusions or minimum order value.",
    discountVisit: "Visit brand shop",
    discountEmpty: "No discount codes yet",
    discountEmptyHint: "Add a brand’s offer and enable it when it is ready to share.",
    discountDeleteConfirm: "Delete this discount code?",
    discountForbidden: "You do not have permission to manage discount codes.",
    discountInvalidData: "Check the form fields and try again.",
    discountBrandRequired: "Enter the brand name.",
    discountCodeRequired: "Enter the discount code.",
    discountInvalidCode: "The code cannot contain spaces or line breaks.",
    discountOfferRequired: "Enter the offer headline in both German and English.",
    discountInvalidUrl: "Enter a full http:// or https:// shop URL without a username or password.",
    discountInvalidExpiry: "Enter a valid expiry date.",
    discountInvalidOrder: "Sort order must be a whole number from 0 to 100000.",
    discountTextTooLong: "A field is too long. Keep the brand under 120, code under 100, headline under 160 and description under 3000 characters.",
    discountSaveFailed: "The offer could not be saved. Please try again.",
    discountDeleteFailed: "The offer could not be deleted. Please try again.",
    // nav
    guide: "Guide (0 to 100)",
    overview: "Overview",
    appointments: "Appointments",
    calendar: "Calendar",
    clients: "Clients",
    services: "Services",
    portfolio: "Portfolio",
    testimonials: "Testimonials",
    blog: "Blog",
    mediaLibrary: "Media Library",
    seo: "SEO",
    settings: "Settings",
    // header
    welcome: "Welcome",
    signOut: "Sign Out",
    // dashboard
    dashboard: "Dashboard",
    dashboardSub: "Overview of your beauty business",
    totalAppointments: "Total Appointments",
    pending: "Pending",
    confirmed: "Confirmed",
    completed: "Completed",
    cancelled: "Cancelled",
    noShow: "No Show",
    recentAppointments: "Recent Appointments",
    viewAll: "View all →",
    noAppointmentsYet: "No appointments yet",
    client: "Client",
    service: "Service",
    date: "Date",
    booked: "Booked",
    status: "Status",
    // appointments page
    all: "All",
    noAppointmentsFound: "No appointments found",
    phone: "Phone",
    appointment: "Appointment",
    actions: "Actions",
    confirm: "✓ Confirm",
    decline: "✕ Decline",
    reason: "Reason (optional)",
    confirmDecline: "Confirm Decline",
    deleteAppointment: "Delete appointment?",
    // calendar
    noUpcoming: "No upcoming appointments",
    // clients
    name: "Name",
    contact: "Contact",
    tags: "Tags",
    noClientsYet: "No clients yet",
    // pagination
    prev: "Prev",
    next: "Next",
    page: "Page",
    of: "of",
    // page headers
    addNew: "Add New",
    newAppointment: "New Appointment",
    appointmentsDesc: "Manage all booking requests and appointments",
    calendarDesc: "Upcoming confirmed and pending appointments",
    newClient: "New Client",
    clientsDesc: "Manage client profiles and history",
    servicesTitle: "Services",
    servicesDesc: "Manage beauty services",
    newService: "New Service",
    active: "Active",
    inactive: "Inactive",
    portfolioTitle: "Portfolio",
    portfolioDesc: "Manage portfolio categories and gallery items",
    categories: "Categories",
    addCategory: "Add Category",
    addPortfolioItem: "Add Portfolio Item",
    portfolioItems: "Portfolio Items",
    items: "items",
    itemDetails: "Item Details",
    category: "Category",
    linkedService: "Linked Service (optional)",
    image: "Image",
    titleDe: "Title (DE)",
    titleEn: "Title (EN)",
    altTextDe: "Alt Text (DE)",
    altTextEn: "Alt Text (EN)",
    descriptionDe: "Description (DE)",
    descriptionEn: "Description (EN)",
    nameDe: "Name (DE)",
    nameEn: "Name (EN)",
    german: "German",
    english: "English",
    testimonialsTitle: "Testimonials",
    testimonialsDesc: "Manage client reviews",
    addTestimonial: "Add Testimonial",
    featuredLabel: "Featured",
    clientName: "Client Name",
    eventType: "Event Type",
    rating: "Rating (1-5)",
    contentDe: "Content (DE)",
    contentEn: "Content (EN)",
    delete: "Delete",
    edit: "Edit",
    none: "None",
    featured: "Featured",
    slug: "Slug",
    sortOrder: "Sort Order",
    blogDesc: "Manage blog posts and categories",
    newPost: "New Post",
    posts: "Posts",
    save: "Save",
    coverImage: "Cover Image",
    coverImageHint: "Wide cover image (recommended: 1200×630)",
    postSettings: "Post Settings",
    tagsHint: "Tags (comma-separated)",
    draft: "Draft",
    published: "Published",
    archived: "Archived",
    excerptDe: "Excerpt (DE)",
    excerptEn: "Excerpt (EN)",
    newBlogPost: "New Blog Post",
    editBlogPost: "Edit Blog Post",
    mediaLibraryDesc: "Manage images and media assets",
    addMedia: "Add Media",
    altText: "Alt Text",
    folder: "Folder",
    editMedia: "Edit Media",
    email: "Email",
    settingsDesc: "Business info, hours, and blocked dates",
    businessInfo: "Business Information",
    businessName: "Business Name",
    instagramUrl: "Instagram URL",
    location: "Location",
    saveSettings: "Save Settings",
    workingHours: "Working Hours",
    day: "Day",
    startTime: "Start Time",
    endTime: "End Time",
    allDay: "All Day",
    timeHint: 'Format: HH:MM — e.g. "10:00"',
    addRule: "Add Rule",
    blockedDates: "Blocked Dates",
    addBlockedDate: "Add Blocked Date",
    integrations: "Integrations",
    editWorkingHours: "Edit Working Hours",
    // edit pages
    editAppointment: "Edit Appointment",
    appointmentDetails: "Appointment Details",
    clientNotes: "Client Notes",
    internalNotes: "Internal Notes",
    locale: "Locale",
    editClient: "Edit Client",
    clientInfo: "Client Information",
    firstName: "First Name",
    lastName: "Last Name",
    notes: "Notes",
    vipClient: "VIP Client",
    editService: "Edit Service",
    serviceDetails: "Service Details",
    icon: "Icon",
    durationMinutes: "Duration (minutes)",
    bufferMinutes: "Buffer (minutes)",
    germanContent: "German Content",
    englishContent: "English Content",
    shortDescDe: "Short Description (DE)",
    shortDescEn: "Short Description (EN)",
    editPortfolioItem: "Edit Portfolio Item",
    editTestimonial: "Edit Testimonial",
    testimonial: "Testimonial",
    type: "Type",
  },
  fa: {
    discounts: "کدهای تخفیف",
    discountsDesc: "مدیریت پیشنهاد برندها، کدهای تخفیف و لینک‌های معرفی.",
    discountNew: "افزودن کد تخفیف",
    discountEdit: "ویرایش کد تخفیف",
    discountDetails: "اطلاعات برند و تخفیف",
    discountBrand: "نام برند",
    discountLogo: "لوگوی برند (اختیاری)",
    discountLogoHint: "برای نتیجه بهتر، لوگوی PNG یا WebP با پس‌زمینه شفاف آپلود کنید.",
    discountLogoChoose: "انتخاب لوگو",
    discountLogoReplace: "جایگزین کردن لوگو",
    discountLogoRemove: "حذف لوگو",
    discountLabel: "Badge مقدار تخفیف",
    discountLabelRequired: "یک Badge کوتاه مثل 20% OFF وارد کنید.",
    discountInvalidLogo: "لوگوی معتبر آپلود کنید.",
    discountClicks: "کلیک روی فروشگاه",
    discountCode: "کد تخفیف",
    discountUrl: "لینک فروشگاه یا لینک معرفی شما",
    discountUrlHint: "لینک کامل دریافتی از برند را همراه با پارامترهای معرفی وارد کنید.",
    discountExpiry: "تاریخ انقضا (اختیاری)",
    discountExpiryHint: "تا پایان این روز به وقت آلمان معتبر است. برای اعتبار بدون محدودیت، خالی بگذارید.",
    discountNoExpiry: "بدون تاریخ انقضا",
    discountExpired: "منقضی‌شده",
    discountPublish: "این تخفیف در سایت نمایش داده شود",
    discountPublishHint: "کدهای منقضی‌شده به‌صورت خودکار پنهان می‌شوند، حتی اگر این گزینه فعال باشد.",
    discountOfferDe: "عنوان پیشنهاد (آلمانی)",
    discountOfferEn: "عنوان پیشنهاد (انگلیسی)",
    discountTermsHint: "شرایط برند، محصولات مستثنا یا حداقل مبلغ خرید را در توضیحات بنویسید.",
    discountVisit: "رفتن به سایت برند",
    discountEmpty: "هنوز کد تخفیفی ثبت نشده است",
    discountEmptyHint: "پیشنهاد یک برند را اضافه کنید و وقتی آماده بود، نمایش آن را فعال کنید.",
    discountDeleteConfirm: "این کد تخفیف حذف شود؟",
    discountForbidden: "شما اجازه مدیریت کدهای تخفیف را ندارید.",
    discountInvalidData: "اطلاعات فرم را بررسی کنید و دوباره تلاش کنید.",
    discountBrandRequired: "نام برند را وارد کنید.",
    discountCodeRequired: "کد تخفیف را وارد کنید.",
    discountInvalidCode: "کد تخفیف نباید فاصله یا خط جدید داشته باشد.",
    discountOfferRequired: "عنوان پیشنهاد را به آلمانی و انگلیسی وارد کنید.",
    discountInvalidUrl: "لینک کامل فروشگاه را با http:// یا https:// و بدون نام کاربری و رمز عبور وارد کنید.",
    discountInvalidExpiry: "تاریخ انقضای معتبر وارد کنید.",
    discountInvalidOrder: "ترتیب نمایش باید عدد صحیح بین ۰ تا ۱۰۰۰۰۰ باشد.",
    discountTextTooLong: "متن بیش از حد طولانی است؛ نام برند حداکثر ۱۲۰، کد ۱۰۰، عنوان ۱۶۰ و توضیحات ۳۰۰۰ کاراکتر باشد.",
    discountSaveFailed: "ذخیره تخفیف انجام نشد. دوباره تلاش کنید.",
    discountDeleteFailed: "حذف تخفیف انجام نشد. دوباره تلاش کنید.",
    // nav
    guide: "آموزش صفر تا صد",
    overview: "نمای کلی",
    appointments: "رزروها",
    calendar: "تقویم",
    clients: "مشتریان",
    services: "خدمات",
    portfolio: "پورتفولیو",
    testimonials: "نظرات",
    blog: "وبلاگ",
    mediaLibrary: "کتابخانه رسانه",
    seo: "سئو",
    settings: "تنظیمات",
    // header
    welcome: "خوش آمدید",
    signOut: "خروج",
    // dashboard
    dashboard: "داشبورد",
    dashboardSub: "نمای کلی کسب‌وکار زیبایی شما",
    totalAppointments: "کل رزروها",
    pending: "در انتظار",
    confirmed: "تأیید شده",
    completed: "انجام شده",
    cancelled: "لغو شده",
    noShow: "حاضر نشده",
    recentAppointments: "رزروهای اخیر",
    viewAll: "← مشاهده همه",
    noAppointmentsYet: "هنوز رزروی ثبت نشده",
    client: "مشتری",
    service: "خدمت",
    date: "تاریخ",
    booked: "ثبت در",
    status: "وضعیت",
    // appointments page
    all: "همه",
    noAppointmentsFound: "رزروی یافت نشد",
    phone: "تلفن",
    appointment: "رزرو",
    actions: "عملیات",
    confirm: "✓ تأیید",
    decline: "✕ رد",
    reason: "دلیل (اختیاری)",
    confirmDecline: "تأیید رد",
    deleteAppointment: "حذف رزرو؟",
    // calendar
    noUpcoming: "رزرو آینده‌ای وجود ندارد",
    // clients
    name: "نام",
    contact: "اطلاعات تماس",
    tags: "برچسب‌ها",
    noClientsYet: "هنوز مشتری‌ای ثبت نشده",
    // pagination
    prev: "قبلی",
    next: "بعدی",
    page: "صفحه",
    of: "از",
    // page headers
    addNew: "افزودن",
    newAppointment: "رزرو جدید",
    appointmentsDesc: "مدیریت تمام درخواست‌ها و رزروها",
    calendarDesc: "رزروهای تأیید شده و در انتظار",
    newClient: "مشتری جدید",
    clientsDesc: "مدیریت پروفایل و سابقه مشتریان",
    servicesTitle: "خدمات",
    servicesDesc: "مدیریت خدمات زیبایی",
    newService: "خدمت جدید",
    active: "فعال",
    inactive: "غیرفعال",
    portfolioTitle: "پورتفولیو",
    portfolioDesc: "مدیریت دسته‌بندی‌ها و آیتم‌های گالری",
    categories: "دسته‌بندی‌ها",
    addCategory: "افزودن دسته‌بندی",
    addPortfolioItem: "افزودن آیتم",
    portfolioItems: "آیتم‌های پورتفولیو",
    items: "آیتم",
    itemDetails: "جزئیات آیتم",
    category: "دسته‌بندی",
    linkedService: "خدمت مرتبط (اختیاری)",
    image: "تصویر",
    titleDe: "عنوان (آلمانی)",
    titleEn: "عنوان (انگلیسی)",
    altTextDe: "متن جایگزین (آلمانی)",
    altTextEn: "متن جایگزین (انگلیسی)",
    descriptionDe: "توضیحات (آلمانی)",
    descriptionEn: "توضیحات (انگلیسی)",
    nameDe: "نام (آلمانی)",
    nameEn: "نام (انگلیسی)",
    german: "آلمانی",
    english: "انگلیسی",
    testimonialsTitle: "نظرات",
    testimonialsDesc: "مدیریت نظرات مشتریان",
    addTestimonial: "افزودن نظر",
    featuredLabel: "ویژه",
    clientName: "نام مشتری",
    eventType: "نوع رویداد",
    rating: "امتیاز (۱-۵)",
    contentDe: "متن (آلمانی)",
    contentEn: "متن (انگلیسی)",
    delete: "حذف",
    edit: "ویرایش",
    none: "هیچ‌کدام",
    featured: "ویژه",
    slug: "اسلاگ",
    sortOrder: "ترتیب",
    blogDesc: "مدیریت مطالب و دسته‌بندی‌های وبلاگ",
    newPost: "مطلب جدید",
    posts: "مطالب",
    save: "ذخیره",
    coverImage: "تصویر کاور",
    coverImageHint: "تصویر افقی (پیشنهاد: ۱۲۰۰×۶۳۰)",
    postSettings: "تنظیمات مطلب",
    tagsHint: "برچسب‌ها (با کاما جدا کنید)",
    draft: "پیش‌نویس",
    published: "منتشر شده",
    archived: "بایگانی",
    excerptDe: "خلاصه (آلمانی)",
    excerptEn: "خلاصه (انگلیسی)",
    newBlogPost: "مطلب جدید وبلاگ",
    editBlogPost: "ویرایش مطلب وبلاگ",
    mediaLibraryDesc: "مدیریت تصاویر و فایل‌های رسانه",
    addMedia: "افزودن رسانه",
    altText: "متن جایگزین",
    folder: "پوشه",
    editMedia: "ویرایش رسانه",
    email: "ایمیل",
    settingsDesc: "اطلاعات کسب‌وکار، ساعات کاری و تاریخ‌های مسدود",
    businessInfo: "اطلاعات کسب‌وکار",
    businessName: "نام کسب‌وکار",
    instagramUrl: "آدرس اینستاگرام",
    location: "موقعیت مکانی",
    saveSettings: "ذخیره تنظیمات",
    workingHours: "ساعات کاری",
    day: "روز",
    startTime: "ساعت شروع",
    endTime: "ساعت پایان",
    allDay: "تمام روز",
    timeHint: "فرمت: HH:MM — مثلاً «۱۰:۰۰»",
    addRule: "افزودن قانون",
    blockedDates: "تاریخ‌های مسدود",
    addBlockedDate: "افزودن تاریخ مسدود",
    integrations: "یکپارچه‌سازی‌ها",
    editWorkingHours: "ویرایش ساعات کاری",
    // edit pages
    editAppointment: "ویرایش رزرو",
    appointmentDetails: "جزئیات رزرو",
    clientNotes: "یادداشت مشتری",
    internalNotes: "یادداشت داخلی",
    locale: "زبان",
    editClient: "ویرایش مشتری",
    clientInfo: "اطلاعات مشتری",
    firstName: "نام",
    lastName: "نام خانوادگی",
    notes: "یادداشت",
    vipClient: "مشتری VIP",
    editService: "ویرایش خدمت",
    serviceDetails: "جزئیات خدمت",
    icon: "آیکون",
    durationMinutes: "مدت زمان (دقیقه)",
    bufferMinutes: "زمان فاصله (دقیقه)",
    germanContent: "محتوای آلمانی",
    englishContent: "محتوای انگلیسی",
    shortDescDe: "توضیح کوتاه (آلمانی)",
    shortDescEn: "توضیح کوتاه (انگلیسی)",
    editPortfolioItem: "ویرایش آیتم پورتفولیو",
    editTestimonial: "ویرایش نظر",
    testimonial: "نظر",
    type: "نوع",
  },
};

const AdminLangContext = createContext<AdminLangContextValue>({
  lang: "en",
  setLang: () => {},
  t: (k) => translations["en"][k] ?? k,
  dir: "ltr",
});

export function AdminLangProvider({ children }: { children: React.ReactNode }) {
  // Always start as "en" so the server render and the first client render
  // match (avoids hydration mismatch). The stored preference is applied in an
  // effect after hydration.
  const [lang, setLangState] = useState<AdminLang>("en");

  useEffect(() => {
    const stored = window.localStorage.getItem(STORAGE_KEY);
    if (stored === "fa" || stored === "en") {
      setLangState(stored);
    }
  }, []);

  function setLang(l: AdminLang) {
    setLangState(l);
    try {
      window.localStorage.setItem(STORAGE_KEY, l);
    } catch {}
  }

  function t(key: string): string {
    return translations[lang][key] ?? translations["en"][key] ?? key;
  }

  return (
    <AdminLangContext.Provider value={{ lang, setLang, t, dir: lang === "fa" ? "rtl" : "ltr" }}>
      {children}
    </AdminLangContext.Provider>
  );
}

export function useAdminLang() {
  return useContext(AdminLangContext);
}
