import { spawnSync, spawn } from "node:child_process";
import { randomBytes } from "node:crypto";
import { existsSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import nextEnv from "@next/env";

const { loadEnvConfig } = nextEnv;

const root = fileURLToPath(new URL("../", import.meta.url));
process.chdir(root);
const mode = process.argv[2];
if (!["setup", "dev", "stop"].includes(mode)) {
  throw new Error("Use: node scripts/local.mjs setup|dev|stop");
}

const envPath = path.join(root, ".env.development.local");
if (!existsSync(envPath)) {
  if (mode !== "setup") throw new Error("Run npm run local:setup first.");
  const password = randomBytes(24).toString("hex");
  const url = `postgresql://sepideh:${password}@127.0.0.1:5433/sepideh_local?schema=public`;
  writeFileSync(envPath, [
    "# Local development only. Generated by npm run local:setup.",
    `LOCAL_POSTGRES_PASSWORD=${password}`,
    `DATABASE_URL=${url}`,
    `DIRECT_URL=${url}`,
    `AUTH_SECRET=${randomBytes(32).toString("hex")}`,
    "AUTH_URL=http://localhost:3000",
    "NEXTAUTH_URL=http://localhost:3000",
    "AUTH_TRUST_HOST=true",
    "NEXT_PUBLIC_SITE_URL=http://localhost:3000",
    "ADMIN_EMAIL=admin@sepideh.local",
    "ADMIN_PASSWORD=SepidehLocal2026!",
    "RESEND_API_KEY=",
    "\n",
  ].join("\n"), { flag: "wx" });
}

loadEnvConfig(root, true);
// The local runner must never push schemas or seed data into a remote database.
for (const key of ["DATABASE_URL", "DIRECT_URL"]) {
  const url = new URL(process.env[key] ?? "");
  if (url.protocol !== "postgresql:" || url.hostname !== "127.0.0.1" || url.port !== "5433" || url.pathname !== "/sepideh_local") {
    throw new Error(`${key} must point to the local sepideh_local database on 127.0.0.1:5433.`);
  }
}

function run(command, args) {
  const result = spawnSync(command, args, { cwd: root, stdio: "inherit", env: process.env, windowsHide: true });
  if (result.error) throw result.error;
  if (result.status !== 0) process.exit(result.status ?? 1);
}

const compose = ["compose", "--env-file", envPath, "-f", "compose.local.yml"];
if (mode === "stop") {
  run("docker", [...compose, "stop"]);
} else if (mode === "setup") {
  run("docker", [...compose, "up", "-d", "--wait"]);
  run(process.execPath, ["node_modules/prisma/build/index.js", "db", "push"]);
  run(process.execPath, ["--import", "tsx", "prisma/seed.ts"]);
  console.log("\nLocal database ready. Start with npm run dev:local, then open http://localhost:3000/admin/login.");
  console.log(`Local admin email: ${process.env.ADMIN_EMAIL}. Password is in .env.development.local.`);
} else {
  const child = spawn(process.execPath, ["node_modules/next/dist/bin/next", "dev", "--hostname", "0.0.0.0", "--port", "3000"], {
    cwd: root, stdio: "inherit", env: process.env, windowsHide: true,
  });
  child.on("error", (error) => { console.error(error.message); process.exitCode = 1; });
  child.on("exit", (code) => { process.exitCode = code ?? 0; });
}
